#!/usr/bin/env python3
import pysftp, yaml, socket

###### init vars
local_host_name = socket.gethostname()
local_links_fn = "links_"+ local_host_name +".txt"
params = yaml.safe_load(open("params.yaml"))
Hostname = params["hostname"]
Username = params["username"]
Password = params["password"]

###### Connect
with pysftp.Connection(host=Hostname, username=Username, password=Password) as sftp:
    print("Connection successfully established ... ")
    # Switch to a remote directory
    sftp.cwd('/downloads/links')

    #Upload the local links file
    sftp.put(local_links_fn)

    # Download all the none-native links files
    directory_structure = sftp.listdir_attr()
    for attr in directory_structure:
        fn = attr.filename
        if fn.endswith(".txt") and fn!=local_links_fn:
            sftp.get(fn)

