#!/usr/bin/env python3
import pysftp, yaml, socket

print("Launching")
###### init vars
local_host_name = socket.gethostname()
local_links_fn = "links_"+ local_host_name +".yml"
params = yaml.safe_load(open("params.yml"))
Hostname = params["hostname"]
Username = params["username"]
Password = params["password"]

###### Connect
with pysftp.Connection(host=Hostname, username=Username, password=Password) as sftp:
    print("Connection successfully established ... ")
    # Switch to a remote directory
    sftp.cwd('/downloads/links')

    #Upload the local links file
    print(f'    Uploading local links file "{local_links_fn}"')
    sftp.put(local_links_fn)

    # Download all the none-native links files
    directory_structure = sftp.listdir_attr()
    for attr in directory_structure:
        fn = attr.filename
        if fn.endswith(".yml") and fn!=local_links_fn:
            print(f'    Downloading remote links file "{fn}"')
            sftp.get(fn)
print("Done.")
